apiVersion: apps/v1
kind: Deployment
metadata:
  name: genomics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genomics
  template:
    metadata:
      labels:
        app: genomics
    spec:
      containers:
        - name: genomics
          image: ronn/genomics:1.0
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "genosentinel"
            - name: DB_USER
              value: "appuser"
            - name: DB_PASSWORD
              value: "apppass"
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: genomics
spec:
  selector:
    app: genomics
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
